CREATE OR REPLACE TASK REAL_ESTATE_ANALYTICS.OPS.TASK_DBT_BUILD
    WAREHOUSE = RE_ETL_WH
    SCHEDULE = '5 MINUTE'
AS
    EXECUTE DBT PROJECT
        REAL_ESTATE_ANALYTICS.DW.REAL_ESTATE_ANALYTICS_DBT
        ARGS = 'build --target dev';

ALTER TASK REAL_ESTATE_ANALYTICS.OPS.TASK_DBT_BUILD RESUME;

SHOW TASKS IN SCHEMA REAL_ESTATE_ANALYTICS.OPS;

ALTER TASK REAL_ESTATE_ANALYTICS.OPS.TASK_DBT_BUILD SUSPEND;


SELECT *
FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'REAL_ESTATE_ANALYTICS.RAW.RAW_TRANSACTIONS',
        START_TIME => DATEADD('MINUTE', -10, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;


