SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    QUERY_ID,
    ERROR_MESSAGE
FROM TABLE(
    SNOWFLAKE.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_DBT_BUILD',
        SCHEDULED_TIME_RANGE_START => DATEADD('hour', -1, CURRENT_TIMESTAMP()),
        RESULT_LIMIT => 10
    )
)
ORDER BY SCHEDULED_TIME DESC;

SELECT *
FROM TABLE(
    REAL_ESTATE_ANALYTICS.INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'REAL_ESTATE_ANALYTICS.RAW.RAW_TRANSACTIONS',
        START_TIME => DATEADD('MINUTE', -10, CURRENT_TIMESTAMP())
    )
)
ORDER BY LAST_LOAD_TIME DESC;

SELECT
    TXN_ID,
    TXN_LINE_ID,
    PROPERTY_ID,
    CITY_ID,
    DEVELOPER_ID,
    SALE_PRICE_LAKHS,
    TXN_STATUS,
    UPDATED_AT
FROM REAL_ESTATE_ANALYTICS.RAW.RAW_TRANSACTIONS
WHERE TXN_ID IN ('TX7026', 'TX7027')
ORDER BY TXN_ID;


SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    QUERY_ID
FROM TABLE(
    REAL_ESTATE_ANALYTICS.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'REAL_ESTATE_ANALYTICS.OPS.TASK_DBT_BUILD',
        RESULT_LIMIT => 5
    )
)
ORDER BY SCHEDULED_TIME DESC;

SELECT
    NAME,
    STATE,
    SCHEDULED_TIME,
    COMPLETED_TIME,
    QUERY_ID
FROM TABLE(
    REAL_ESTATE_ANALYTICS.INFORMATION_SCHEMA.TASK_HISTORY(
        RESULT_LIMIT => 20
    )
)
WHERE NAME = 'TASK_DBT_BUILD'
ORDER BY SCHEDULED_TIME DESC;

SELECT
    TXN_ID,
    TXN_LINE_ID,
    SK_PROPERTY,
    SK_CITY,
    SK_DEVELOPER,
    SALE_PRICE,
    TXN_STATUS
FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION
WHERE TXN_ID IN ('TX7026', 'TX7027')
ORDER BY TXN_ID;

SELECT COUNT(*) AS FACT_COUNT
FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION;

SELECT
    TXN_ID,
    TXN_LINE_ID,
    COUNT(*) AS CNT
FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION
GROUP BY TXN_ID, TXN_LINE_ID
HAVING COUNT(*) > 1;




ALTER TASK REAL_ESTATE_ANALYTICS.OPS.TASK_DBT_BUILD SUSPEND;

SHOW TASKS LIKE 'TASK_DBT_BUILD';



DESC TABLE REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION;

SELECT *
FROM REAL_ESTATE_ANALYTICS.DW.DIM_DATE
WHERE DATE_VALUE = '2026-01-01';

SELECT
    TXN_ID,
    TXN_LINE_ID,
    SK_TXN_DATE
FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION
WHERE TXN_ID IN ('TX7026', 'TX7027')
ORDER BY TXN_ID;