{{ config(
    materialized='dim_city_merge'
) }}

SELECT
    CITY_ID,
    CITY_NAME,
    STATE,
    REGION,
    CITY_CLASS,
    GEO_TYPE,
    POPULATION,
    AREA_SQKM
FROM {{ source('raw', 'RAW_CITIES') }}
WHERE CITY_ID IS NOT NULL

QUALIFY ROW_NUMBER() OVER (
    PARTITION BY CITY_ID
    ORDER BY UPDATED_AT DESC, LOAD_TS DESC, SOURCE_FILE_NAME DESC
) = 1