USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA DW;

// DIM_DATE

CREATE OR REPLACE TABLE DIM_DATE
(
    SK_DATE        NUMBER(8,0) NOT NULL,
    DATE_VALUE     DATE NOT NULL,
    YEAR           NUMBER(4,0),
    QUARTER        VARCHAR(2),
    MONTH          NUMBER(2,0),
    WEEK_OF_YEAR   NUMBER(2,0),
    IS_WEEKEND     BOOLEAN,

    CONSTRAINT PK_DIM_DATE PRIMARY KEY (SK_DATE),
    CONSTRAINT UK_DIM_DATE_DATE_VALUE UNIQUE (DATE_VALUE)
);


// DIM_CITY

CREATE OR REPLACE TABLE DIM_CITY
(
    SK_CITY        NUMBER AUTOINCREMENT NOT NULL,
    CITY_ID        VARCHAR NOT NULL,
    CITY_NAME      VARCHAR,
    STATE          VARCHAR,
    REGION         VARCHAR,
    CITY_CLASS     VARCHAR,
    GEO_TYPE       VARCHAR,
    POPULATION     NUMBER,
    AREA_SQKM      NUMBER(18,2),

    CONSTRAINT PK_DIM_CITY PRIMARY KEY (SK_CITY),
    CONSTRAINT UK_DIM_CITY_CITY_ID UNIQUE (CITY_ID)
);


DROP TABLE IF EXISTS DW.DIM_CITY;



// DIM_DEVELOPER

CREATE OR REPLACE TABLE DIM_DEVELOPER
(
    SK_DEVELOPER      NUMBER AUTOINCREMENT NOT NULL,
    DEVELOPER_ID      VARCHAR NOT NULL,
    DEVELOPER_NAME    VARCHAR,
    DEVELOPER_TIER    VARCHAR,
    FOCUS_SEGMENT     VARCHAR,
    HQ_CITY           VARCHAR,
    HQ_STATE          VARCHAR,
    STATUS             VARCHAR,

    EFF_START_TS      TIMESTAMP_NTZ,
    EFF_END_TS        TIMESTAMP_NTZ,
    IS_CURRENT        BOOLEAN,
    HASH_DIFF         VARCHAR,

    CONSTRAINT PK_DIM_DEVELOPER PRIMARY KEY (SK_DEVELOPER)
);


// DIM_PROPERTY

CREATE OR REPLACE TABLE DIM_PROPERTY
(
    SK_PROPERTY       NUMBER AUTOINCREMENT NOT NULL,
    PROPERTY_ID       VARCHAR NOT NULL,
    PROPERTY_TYPE     VARCHAR,
    SEGMENT           VARCHAR,
    BHK               NUMBER,
    AREA_SQFT         NUMBER(18,2),
    STATUS            VARCHAR,
    AMENITY_TIER      VARCHAR,
    POSSESSION        NUMBER(4,0),

    HASH_DIFF         VARCHAR,
    EFF_START_TS      TIMESTAMP_NTZ,
    EFF_END_TS        TIMESTAMP_NTZ,
    IS_CURRENT        BOOLEAN,

    CONSTRAINT PK_DIM_PROPERTY PRIMARY KEY (SK_PROPERTY)
);

ALTER TABLE DW.DIM_PROPERTY
RENAME COLUMN POSSESSION TO POSSESSION_YEAR;

// FACT_TRANSACTION

CREATE OR REPLACE TABLE FACT_TRANSACTION
(
    TXN_ID            VARCHAR NOT NULL,
    TXN_LINE_ID       NUMBER NOT NULL,

    SK_TXN_DATE       NUMBER(8,0),
    SK_CITY           NUMBER,
    SK_DEVELOPER      NUMBER,
    SK_PROPERTY       NUMBER,

    LIST_PRICE        NUMBER(18,2),
    SALE_PRICE        NUMBER(18,2),
    DISCOUNT_PCT      NUMBER(5,2),

    BUYER_SEGMENT     VARCHAR,
    CHANNEL           VARCHAR,

    TXN_STATUS        VARCHAR,
    LOAN_REQ          VARCHAR,

    CONSTRAINT PK_FACT_TRANSACTION
        PRIMARY KEY (TXN_ID, TXN_LINE_ID),

    CONSTRAINT FK_FACT_DATE
        FOREIGN KEY (SK_TXN_DATE)
        REFERENCES DIM_DATE(SK_DATE),

    CONSTRAINT FK_FACT_CITY
        FOREIGN KEY (SK_CITY)
        REFERENCES DIM_CITY(SK_CITY),

    CONSTRAINT FK_FACT_DEVELOPER
        FOREIGN KEY (SK_DEVELOPER)
        REFERENCES DIM_DEVELOPER(SK_DEVELOPER),

    CONSTRAINT FK_FACT_PROPERTY
        FOREIGN KEY (SK_PROPERTY)
        REFERENCES DIM_PROPERTY(SK_PROPERTY)
);