-- The date data comes from the raw_transaction dates source

-- Date dim loading

USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA DW;

TRUNCATE TABLE DW.DIM_DATE;
drop table dim_date;
TRUNCATE TABLE FACT_TRANSACTION;
TRUNCATE TABLE DIM_PROPERTY;
TRUNCATE TABLE DIM_DEVELOPER;
TRUNCATE TABLE DIM_CITY;
select * from dim_date;
select * from fact_transaction;
select * from dim_property;
select * from dim_city;
select * from dim_developer;


INSERT INTO DIM_DATE
(
    SK_DATE,
    DATE_VALUE,
    YEAR,
    QUARTER,
    MONTH,
    WEEK_OF_YEAR,
    IS_WEEKEND
)
SELECT DISTINCT
    TO_NUMBER(TO_CHAR(TXN_DATE, 'YYYYMMDD')) AS SK_DATE,
    TXN_DATE AS DATE_VALUE,
    YEAR(TXN_DATE) AS YEAR,
    'Q' || QUARTER(TXN_DATE) AS QUARTER,
    MONTH(TXN_DATE) AS MONTH,
    WEEKISO(TXN_DATE) AS WEEK_OF_YEAR,
    DAYOFWEEKISO(TXN_DATE) IN (6, 7) AS IS_WEEKEND

FROM RAW.RAW_TRANSACTIONS

WHERE TXN_DATE IS NOT NULL;


SELECT *
FROM DW.DIM_DATE
ORDER BY DATE_VALUE;
DESC TABLE DW.DIM_DATE;
desc table dw.dim_city;

SELECT
    COUNT(*) AS DATE_ROWS,
    MIN(DATE_VALUE) AS MIN_DATE,
    MAX(DATE_VALUE) AS MAX_DATE
FROM DW.DIM_DATE;


-- City dim loading
--  The city data from raw_city source

INSERT INTO DIM_CITY
(
    CITY_ID,
    CITY_NAME,
    STATE,
    REGION,
    CITY_CLASS,
    GEO_TYPE,
    POPULATION,
    AREA_SQKM
)
SELECT
    CITY_ID,
    CITY_NAME,
    STATE,
    REGION,
    CITY_CLASS,
    GEO_TYPE,
    POPULATION,
    AREA_SQKM
FROM RAW.RAW_CITIES;

SELECT *
FROM DW.DIM_CITY
ORDER BY SK_CITY;

desc table dw.dim_city;

SELECT COUNT(*) AS CITY_COUNT
FROM DW.DIM_CITY;

-- Developer dim loading
-- Developer gets data from raw_developer source

TRUNCATE TABLE DW.DIM_DEVELOPER;

INSERT INTO DIM_DEVELOPER
(
    DEVELOPER_ID,
    DEVELOPER_NAME,
    DEVELOPER_TIER,
    FOCUS_SEGMENT,
    HQ_CITY,
    HQ_STATE,
    STATUS,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    HASH_DIFF
)
SELECT
    DEVELOPER_ID,
    DEVELOPER_NAME,
    DEVELOPER_TIER,
    FOCUS_SEGMENT,
    HQ_CITY,
    HQ_STATE,
    STATUS,

    LOAD_TS AS EFF_START_TS,

    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFF_END_TS,

    TRUE AS IS_CURRENT,

    MD5(
        COALESCE(DEVELOPER_TIER, '') || '|' ||
        COALESCE(FOCUS_SEGMENT, '')  || '|' ||
        COALESCE(HQ_CITY, '')         || '|' ||
        COALESCE(HQ_STATE, '')        || '|' ||
        COALESCE(STATUS, '')
    ) AS HASH_DIFF

FROM RAW.RAW_DEVELOPERS;

SELECT * 
FROM DW.DIM_DEVELOPER
ORDER BY SK_DEVELOPER;

SELECT COUNT(*) AS DEVELOPER_COUNT
FROM DW.DIM_DEVELOPER;


-- testing SCD2 in Developer

CREATE OR REPLACE TEMP TABLE TMP_DEVELOPER_CHANGE AS
SELECT *
FROM RAW.RAW_DEVELOPERS;

UPDATE TMP_DEVELOPER_CHANGE
SET DEVELOPER_TIER = 'Tier-2'
WHERE DEVELOPER_ID = 'DV001';

SELECT
    DEVELOPER_ID,
    DEVELOPER_TIER,
    FOCUS_SEGMENT,
    HQ_CITY,
    HQ_STATE,
    STATUS,

    MD5(
        COALESCE(DEVELOPER_TIER, '') || '|' ||
        COALESCE(FOCUS_SEGMENT, '')  || '|' ||
        COALESCE(HQ_CITY, '')         || '|' ||
        COALESCE(HQ_STATE, '')        || '|' ||
        COALESCE(STATUS, '')
    ) AS NEW_HASH
FROM TMP_DEVELOPER_CHANGE
WHERE DEVELOPER_ID = 'DV001';

SELECT
    DEVELOPER_ID,
    HASH_DIFF AS OLD_HASH,
    IS_CURRENT
FROM DW.DIM_DEVELOPER
WHERE DEVELOPER_ID = 'DV001'
  AND IS_CURRENT = TRUE;

SET P_LOAD_TS = CURRENT_TIMESTAMP();

UPDATE DW.DIM_DEVELOPER
SET
    EFF_END_TS = $P_LOAD_TS,
    IS_CURRENT = FALSE
WHERE DEVELOPER_ID = 'DV001'
  AND IS_CURRENT = TRUE;

INSERT INTO DW.DIM_DEVELOPER
(
    DEVELOPER_ID,
    DEVELOPER_NAME,
    DEVELOPER_TIER,
    FOCUS_SEGMENT,
    HQ_CITY,
    HQ_STATE,
    STATUS,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    HASH_DIFF
)
SELECT
    DEVELOPER_ID,
    DEVELOPER_NAME,
    DEVELOPER_TIER,
    FOCUS_SEGMENT,
    HQ_CITY,
    HQ_STATE,
    STATUS,

    $P_LOAD_TS AS EFF_START_TS,

    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFF_END_TS,

    TRUE AS IS_CURRENT,

    MD5(
        COALESCE(DEVELOPER_TIER, '') || '|' ||
        COALESCE(FOCUS_SEGMENT, '')  || '|' ||
        COALESCE(HQ_CITY, '')         || '|' ||
        COALESCE(HQ_STATE, '')        || '|' ||
        COALESCE(STATUS, '')
    ) AS HASH_DIFF

FROM TMP_DEVELOPER_CHANGE
WHERE DEVELOPER_ID = 'DV001';

SELECT
    SK_DEVELOPER,
    DEVELOPER_ID,
    DEVELOPER_TIER,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    HASH_DIFF
FROM DW.DIM_DEVELOPER
WHERE DEVELOPER_ID = 'DV001'
ORDER BY EFF_START_TS;


-- PROPERTY DIM DATA LOADING
-- THE DATA FOR PROPERTY FROM SOURCE RAW_PROPERTY

DESC TABLE DIM_PROPERTY;

INSERT INTO DIM_PROPERTY
(
    PROPERTY_ID,
    PROPERTY_TYPE,
    SEGMENT,
    BHK,
    AREA_SQFT,
    STATUS,
    AMENITY_TIER,
    POSSESSION_YEAR,
    HASH_DIFF,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT
)
SELECT
    PROPERTY_ID,
    PROPERTY_TYPE,
    SEGMENT,
    BHK,
    AREA_SQFT,
    PROJECT_STATUS,
    AMENITY_TIER,
    POSSESSION_YEAR,

    MD5(
        COALESCE(PROPERTY_TYPE, '') || '|' ||
        COALESCE(SEGMENT, '') || '|' ||
        COALESCE(BHK::VARCHAR, '') || '|' ||
        COALESCE(AREA_SQFT::VARCHAR, '') || '|' ||
        COALESCE(POSSESSION_YEAR::VARCHAR, '') || '|' ||
        COALESCE(PROJECT_STATUS, '') || '|' ||
        COALESCE(AMENITY_TIER, '')
    ) AS HASH_DIFF,

    LOAD_TS AS EFF_START_TS,

    '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFF_END_TS,

    TRUE AS IS_CURRENT

FROM RAW.RAW_PROPERTIES;

SELECT *
FROM DW.DIM_PROPERTY
ORDER BY SK_PROPERTY;

SELECT COUNT(*) AS PROPERTY_COUNT
FROM DW.DIM_PROPERTY;


-- FACT TRASACTION DATA FROM RAW_TRANSACTION SOURCE AND OTHER DIM TABLES
-- FACT TRANSCTION DATA LOADING 

USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA DW;

INSERT INTO FACT_TRANSACTION
(
    TXN_ID,
    TXN_LINE_ID,

    SK_TXN_DATE,
    SK_CITY,
    SK_DEVELOPER,
    SK_PROPERTY,

    LIST_PRICE,
    SALE_PRICE,
    DISCOUNT_PCT,

    BUYER_SEGMENT,
    CHANNEL,
    TXN_STATUS,
    LOAN_REQ
)
SELECT
    T.TXN_ID,
    T.TXN_LINE_ID,

    D.SK_DATE,
    C.SK_CITY,
    DEV.SK_DEVELOPER,
    P.SK_PROPERTY,

    T.LIST_PRICE_LAKHS,
    T.SALE_PRICE_LAKHS,
    T.DISCOUNT_PCT,

    T.BUYER_SEGMENT,
    T.SALES_CHANNEL,
    T.TXN_STATUS,
    T.LOAN_REQUIRED

FROM RAW.RAW_TRANSACTIONS T

LEFT JOIN DW.DIM_DATE D
    ON D.DATE_VALUE = T.TXN_DATE

LEFT JOIN DW.DIM_CITY C
    ON C.CITY_ID = T.CITY_ID

LEFT JOIN DW.DIM_DEVELOPER DEV
    ON DEV.DEVELOPER_ID = T.DEVELOPER_ID
   AND DEV.IS_CURRENT = TRUE

LEFT JOIN DW.DIM_PROPERTY P
    ON P.PROPERTY_ID = T.PROPERTY_ID
   AND P.IS_CURRENT = TRUE;

SELECT *
FROM DW.FACT_TRANSACTION
ORDER BY TXN_ID, TXN_LINE_ID;

SELECT COUNT(*) AS FACT_ROW_COUNT
FROM DW.FACT_TRANSACTION;



-- snapshot
SELECT *
FROM DW.SNAP_DEVELOPER
where developer_id='DV001';

DESC TABLE DW.SNAP_DEVELOPER;

DESC TABLE DW.DIM_DEVELOPER;

SELECT *
FROM DW.DIM_DEVELOPER
ORDER BY DEVELOPER_ID, EFF_START_TS;
SELECT COUNT(*) AS ROW_COUNT
FROM DW.DIM_DEVELOPER;


-- testing developer scd2 

UPDATE RAW.RAW_DEVELOPERS
SET DEVELOPER_TIER = 'Tier-2',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE DEVELOPER_ID = 'DV001';


SELECT
    SK_DEVELOPER,
    DEVELOPER_ID,
    DEVELOPER_TIER,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    HASH_DIFF
FROM DW.DIM_DEVELOPER
WHERE DEVELOPER_ID = 'DV001'
ORDER BY EFF_START_TS;

-- dim property 

DESC TABLE DW.DIM_PROPERTY;

-- property snap
SELECT
    PROPERTY_ID,
    PROPERTY_TYPE,
    SEGMENT,
    BHK,
    AREA_SQFT,
    STATUS,
    AMENITY_TIER,
    POSSESSION_YEAR,
    HASH_DIFF,
    DBT_VALID_FROM,
    DBT_VALID_TO
FROM DW.SNAP_PROPERTY
ORDER BY PROPERTY_ID;

DESC TABLE DW.SNAP_PROPERTY;

SELECT
    SK_PROPERTY,
    PROPERTY_ID,
    PROPERTY_TYPE,
    SEGMENT,
    BHK,
    AREA_SQFT,
    STATUS,
    AMENITY_TIER,
    POSSESSION_YEAR,
    EFF_START_TS,
    EFF_END_TS,
    IS_CURRENT,
    HASH_DIFF
FROM DW.DIM_PROPERTY
ORDER BY PROPERTY_ID;

-- propertu scd2 checking 

UPDATE RAW.RAW_PROPERTIES
SET PROJECT_STATUS = 'READY',
    UPDATED_AT = CURRENT_TIMESTAMP()
WHERE PROPERTY_ID = 'PR0001';

SELECT
    PROPERTY_ID,
    STATUS,
    HASH_DIFF,
    DBT_VALID_FROM,
    DBT_VALID_TO
FROM DW.SNAP_PROPERTY
WHERE PROPERTY_ID = 'PR0001'
ORDER BY DBT_VALID_FROM;

select * from dim_property where property_id='PR0001';

-- fact transcation data loading

DESC TABLE DW.FACT_TRANSACTION;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT(SK_TXN_DATE) AS DATE_MATCHED,
    COUNT(SK_CITY) AS CITY_MATCHED,
    COUNT(SK_DEVELOPER) AS DEVELOPER_MATCHED,
    COUNT(SK_PROPERTY) AS PROPERTY_MATCHED
FROM DW.FACT_TRANSACTION;

SELECT
    TXN_ID,
    TXN_LINE_ID,
    COUNT(*) AS CNT
FROM DW.FACT_TRANSACTION
GROUP BY
    TXN_ID,
    TXN_LINE_ID
HAVING COUNT(*) > 1;


