SELECT
    TXN_ID,
    TXN_LINE_ID,
    COUNT(*) AS CNT
FROM DW.FACT_TRANSACTION
GROUP BY TXN_ID, TXN_LINE_ID
HAVING COUNT(*) > 1;

SELECT
    COUNT_IF(SALE_PRICE <= 0) AS INVALID_SALE_PRICE,
    COUNT_IF(DISCOUNT_PCT < 0 OR DISCOUNT_PCT > 100) AS INVALID_DISCOUNT,
    COUNT_IF(TXN_STATUS NOT IN ('BOOKED', 'REGISTERED', 'CANCELLED')) AS INVALID_STATUS
FROM DW.FACT_TRANSACTION;

SELECT
    r.RAW_COUNT,
    f.FACT_COUNT,
    r.RAW_TOTAL_SALES,
    f.FACT_TOTAL_SALES,
    r.RAW_TOTAL_SALES - f.FACT_TOTAL_SALES AS DIFFERENCE
FROM
(
    SELECT
        COUNT(*) AS RAW_COUNT,
        SUM(SALE_PRICE_LAKHS) AS RAW_TOTAL_SALES
    FROM REAL_ESTATE_ANALYTICS.RAW.RAW_TRANSACTIONS
) r
CROSS JOIN
(
    SELECT
        COUNT(*) AS FACT_COUNT,
        SUM(SALE_PRICE) AS FACT_TOTAL_SALES
    FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION
) f;