CREATE WAREHOUSE IF NOT EXISTS RE_ETL_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS REAL_ESTATE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS REAL_ESTATE_ANALYTICS.RAW;

CREATE SCHEMA IF NOT EXISTS REAL_ESTATE_ANALYTICS.DW;

CREATE SCHEMA IF NOT EXISTS REAL_ESTATE_ANALYTICS.SEMANTIC;

CREATE SCHEMA IF NOT EXISTS REAL_ESTATE_ANALYTICS.OPS;

CREATE SCHEMA IF NOT EXISTS REAL_ESTATE_ANALYTICS.GIT;
SHOW GIT REPOSITORIES;
DESCRIBE GIT REPOSITORY
REAL_ESTATE_ANALYTICS.GIT."real-estate-analytics-snowflake";