USE DATABASE REAL_ESTATE_ANALYTICS;

CREATE TABLE IF NOT EXISTS RAW.RAW_CITIES (
    CITY_ID       VARCHAR,
    CITY_NAME     VARCHAR,
    STATE         VARCHAR,
    COUNTRY       VARCHAR,
    REGION        VARCHAR,
    POPULATION    NUMBER,
    AREA_SQKM     NUMBER(12,2),
    CITY_CLASS    VARCHAR,
    GEO_TYPE      VARCHAR,
    UPDATED_AT    TIMESTAMP_NTZ,

    -- Snowpipe / audit metadata
    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME  VARCHAR,
    BATCH_ID           VARCHAR
);


CREATE TABLE IF NOT EXISTS RAW.RAW_DEVELOPERS (
    DEVELOPER_ID     VARCHAR,
    DEVELOPER_NAME   VARCHAR,
    HQ_COUNTRY       VARCHAR,
    DEVELOPER_TIER   VARCHAR,
    FOCUS_SEGMENT    VARCHAR,
    HQ_CITY          VARCHAR,
    HQ_STATE         VARCHAR,
    STATUS           VARCHAR,
    PARTNER_SINCE    DATE,
    UPDATED_AT       TIMESTAMP_NTZ,

    -- Snowpipe / audit metadata
    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME  VARCHAR,
    BATCH_ID           VARCHAR
);


CREATE TABLE IF NOT EXISTS RAW.RAW_PROPERTIES (
    PROPERTY_ID       VARCHAR,
    CITY_ID           VARCHAR,
    DEVELOPER_ID      VARCHAR,
    PROPERTY_TYPE     VARCHAR,
    SEGMENT           VARCHAR,
    BHK               NUMBER,
    AREA_SQFT         NUMBER,
    POSSESSION_YEAR   NUMBER,
    PROJECT_STATUS    VARCHAR,
    AMENITY_TIER      VARCHAR,
    RERA_ID           VARCHAR,
    UPDATED_AT        TIMESTAMP_NTZ,

    -- Snowpipe / audit metadata
    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME  VARCHAR,
    BATCH_ID           VARCHAR
);

CREATE TABLE IF NOT EXISTS RAW.RAW_TRANSACTIONS (
    TXN_ID             VARCHAR,
    TXN_LINE_ID        NUMBER,
    TXN_DATE           DATE,
    PROPERTY_ID        VARCHAR,
    CITY_ID            VARCHAR,
    DEVELOPER_ID       VARCHAR,
    BUYER_SEGMENT      VARCHAR,
    LIST_PRICE_LAKHS   NUMBER(18,2),
    DISCOUNT_PCT       NUMBER(5,2),
    SALE_PRICE_LAKHS   NUMBER(18,2),
    LOAN_REQUIRED      VARCHAR,
    SALES_CHANNEL      VARCHAR,
    TXN_STATUS         VARCHAR,
    PAYMENT_MODE       VARCHAR,
    UPDATED_AT         TIMESTAMP_NTZ,

    -- Snowpipe / audit metadata
    LOAD_TS            TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE_NAME  VARCHAR,
    BATCH_ID           VARCHAR
);

show tables;

select current_timestamp();

SELECT CURRENT_TIMESTAMP(), CURRENT_DATE(), CURRENT_TIME();

SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

ALTER SESSION SET TIMEZONE = 'Asia/Kolkata';

SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

SELECT CURRENT_TIMESTAMP(), CURRENT_DATE(), CURRENT_TIME();