USE DATABASE REAL_ESTATE_ANALYTICS;


USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS ROLE_INGEST;
CREATE ROLE IF NOT EXISTS ROLE_ETL;
CREATE ROLE IF NOT EXISTS ROLE_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_APP_STREAMLIT;
CREATE ROLE IF NOT EXISTS ROLE_ADMIN;

GRANT ROLE ROLE_INGEST TO ROLE SYSADMIN;
GRANT ROLE ROLE_ETL TO ROLE SYSADMIN;
GRANT ROLE ROLE_ANALYST TO ROLE SYSADMIN;
GRANT ROLE ROLE_APP_STREAMLIT TO ROLE SYSADMIN;
GRANT ROLE ROLE_ADMIN TO ROLE SYSADMIN;

SHOW ROLES;