USE DATABASE REAL_ESTATE_ANALYTICS;

-- ROLE_INGEST

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE REAL_ESTATE_ANALYTICS
    TO ROLE ROLE_INGEST;

GRANT USAGE ON SCHEMA REAL_ESTATE_ANALYTICS.RAW
    TO ROLE ROLE_INGEST;

GRANT USAGE ON WAREHOUSE RE_ETL_WH
    TO ROLE ROLE_INGEST;

GRANT INSERT ON ALL TABLES IN SCHEMA REAL_ESTATE_ANALYTICS.RAW
    TO ROLE ROLE_INGEST;

GRANT SELECT ON ALL TABLES IN SCHEMA REAL_ESTATE_ANALYTICS.RAW
    TO ROLE ROLE_INGEST;


-- ROLE_ETL

USE ROLE ACCOUNTADMIN;

GRANT USAGE ON DATABASE REAL_ESTATE_ANALYTICS
    TO ROLE ROLE_ETL;

GRANT USAGE ON SCHEMA REAL_ESTATE_ANALYTICS.RAW
    TO ROLE ROLE_ETL;

GRANT USAGE ON SCHEMA REAL_ESTATE_ANALYTICS.DW
    TO ROLE ROLE_ETL;

GRANT USAGE ON WAREHOUSE RE_ETL_WH
    TO ROLE ROLE_ETL;

GRANT SELECT ON ALL TABLES IN SCHEMA REAL_ESTATE_ANALYTICS.RAW
    TO ROLE ROLE_ETL;

GRANT SELECT, INSERT, UPDATE, DELETE
    ON ALL TABLES IN SCHEMA REAL_ESTATE_ANALYTICS.DW
    TO ROLE ROLE_ETL;


-- ROLE_ANALYST

USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ANALYST;

GRANT USAGE
ON SCHEMA REAL_ESTATE_ANALYTICS.SEMANTIC
TO ROLE ROLE_ANALYST;

GRANT USAGE
ON WAREHOUSE RE_ETL_WH
TO ROLE ROLE_ANALYST;

GRANT SELECT
ON ALL VIEWS IN SCHEMA REAL_ESTATE_ANALYTICS.SEMANTIC
TO ROLE ROLE_ANALYST;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA REAL_ESTATE_ANALYTICS.SEMANTIC
TO ROLE ROLE_ANALYST;

-- ROLE_APP_STREAMLIT

USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_APP_STREAMLIT;

GRANT USAGE
ON SCHEMA REAL_ESTATE_ANALYTICS.SEMANTIC
TO ROLE ROLE_APP_STREAMLIT;

GRANT USAGE
ON WAREHOUSE RE_ETL_WH
TO ROLE ROLE_APP_STREAMLIT;

GRANT SELECT
ON ALL VIEWS IN SCHEMA REAL_ESTATE_ANALYTICS.SEMANTIC
TO ROLE ROLE_APP_STREAMLIT;

GRANT SELECT
ON FUTURE VIEWS IN SCHEMA REAL_ESTATE_ANALYTICS.SEMANTIC
TO ROLE ROLE_APP_STREAMLIT;

-- ROLE_ADMIN
USE ROLE ACCOUNTADMIN;

GRANT USAGE
ON DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ADMIN;

GRANT USAGE
ON ALL SCHEMAS IN DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ADMIN;

GRANT USAGE
ON WAREHOUSE RE_ETL_WH
TO ROLE ROLE_ADMIN;

GRANT ALL PRIVILEGES
ON ALL TABLES IN DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ADMIN;

GRANT ALL PRIVILEGES
ON ALL VIEWS IN DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ADMIN;

GRANT ALL PRIVILEGES
ON FUTURE TABLES IN DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ADMIN;

GRANT ALL PRIVILEGES
ON FUTURE VIEWS IN DATABASE REAL_ESTATE_ANALYTICS
TO ROLE ROLE_ADMIN;

-- CHECKING GRANTED ROLES 

SHOW GRANTS TO ROLE ROLE_ADMIN;

SHOW GRANTS TO ROLE ROLE_ANALYST;

SHOW GRANTS TO ROLE ROLE_APP_STREAMLIT;