USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA SEMANTIC;

CREATE OR REPLACE VIEW SEMANTIC.V_CITY_SALES_DAILY AS
SELECT
    d.DATE_VALUE,
    c.CITY_NAME,
    c.REGION,
    c.CITY_CLASS,

    COUNT(*) AS TRANSACTION_COUNT,
    SUM(f.SALE_PRICE) AS TOTAL_SALES,
    AVG(f.SALE_PRICE) AS AVG_SALE_PRICE,
    AVG(f.DISCOUNT_PCT) AS AVG_DISCOUNT_PCT

FROM DW.FACT_TRANSACTION AS f

JOIN DW.DIM_DATE AS d
    ON f.SK_TXN_DATE = d.SK_DATE

JOIN DW.DIM_CITY AS c
    ON f.SK_CITY = c.SK_CITY

GROUP BY
    d.DATE_VALUE,
    c.CITY_NAME,
    c.REGION,
    c.CITY_CLASS;


SELECT *
FROM SEMANTIC.V_CITY_SALES_DAILY
ORDER BY DATE_VALUE, CITY_NAME;

SELECT COUNT(*)
FROM SEMANTIC.V_CITY_SALES_DAILY;