CREATE OR REPLACE VIEW REAL_ESTATE_ANALYTICS.SEMANTIC.V_DEVELOPER_PERF AS
SELECT
    dev.DEVELOPER_ID,
    dev.DEVELOPER_NAME,
    dev.DEVELOPER_TIER,

    COUNT(*) AS TRANSACTION_COUNT,
    SUM(f.SALE_PRICE) AS TOTAL_SALES,
    AVG(f.SALE_PRICE) AS AVG_SALE_PRICE,
    AVG(f.DISCOUNT_PCT) AS AVG_DISCOUNT_PCT

FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION AS f

JOIN REAL_ESTATE_ANALYTICS.DW.DIM_DEVELOPER AS dev
    ON f.SK_DEVELOPER = dev.SK_DEVELOPER

GROUP BY
    dev.DEVELOPER_ID,
    dev.DEVELOPER_NAME,
    dev.DEVELOPER_TIER;

SHOW VIEWS;

SELECT *
FROM REAL_ESTATE_ANALYTICS.SEMANTIC.V_DEVELOPER_PERF
ORDER BY TOTAL_SALES DESC;