CREATE OR REPLACE VIEW REAL_ESTATE_ANALYTICS.SEMANTIC.V_SEGMENT_MIX AS
SELECT
    f.BUYER_SEGMENT,

    COUNT(*) AS TRANSACTION_COUNT,
    SUM(f.SALE_PRICE) AS TOTAL_SALES,
    AVG(f.SALE_PRICE) AS AVG_SALE_PRICE

FROM REAL_ESTATE_ANALYTICS.DW.FACT_TRANSACTION AS f

GROUP BY
    f.BUYER_SEGMENT;

SELECT *
FROM REAL_ESTATE_ANALYTICS.SEMANTIC.V_SEGMENT_MIX
ORDER BY TOTAL_SALES DESC;