USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA RAW;

CREATE FILE FORMAT IF NOT EXISTS RAW.FF_REAL_ESTATE_CSV
    TYPE = 'CSV'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    EMPTY_FIELD_AS_NULL = TRUE
    NULL_IF = ('', 'NULL', 'null');

SHOW FILE FORMATS;

USE ROLE ACCOUNTADMIN;



LIST @REAL_ESTATE_ANALYTICS.RAW.RE_S3_STAGE;

LIST @RE_S3_STAGE;

DESC STAGE RE_S3_STAGE;

SELECT CURRENT_TIMESTAMP(), CURRENT_DATE(), CURRENT_TIME();

SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

ALTER SESSION SET TIMEZONE = 'Asia/Kolkata';

SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

SELECT CURRENT_TIMESTAMP(), CURRENT_DATE(), CURRENT_TIME();
SHOW STAGES IN SCHEMA REAL_ESTATE_ANALYTICS.RAW;