USE ROLE ACCOUNTADMIN;

USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA RAW;

SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

ALTER SESSION SET TIMEZONE = 'Asia/Kolkata';


-- ALTER PIPE PIPE_CITIES SET PIPE_EXECUTION_PAUSED = TRUE;
-- ALTER PIPE PIPE_DEVELOPERS SET PIPE_EXECUTION_PAUSED = TRUE;
-- ALTER PIPE PIPE_PROPERTIES SET PIPE_EXECUTION_PAUSED = TRUE;
-- ALTER PIPE PIPE_TRANSACTIONS SET PIPE_EXECUTION_PAUSED = TRUE;


-- TRUNCATE TABLE RAW.RAW_CITIES;
-- TRUNCATE TABLE RAW.RAW_DEVELOPERS;
-- TRUNCATE TABLE RAW.RAW_PROPERTIES;
-- TRUNCATE TABLE RAW.RAW_TRANSACTIONS;

-- TRUNCATE TABLE OPS.REJECTS;

CREATE OR REPLACE PIPE PIPE_CITIES
    AUTO_INGEST = FALSE
    COMMENT = 'Snowpipe for cities with error handling'
AS
COPY INTO RAW_CITIES
(
    CITY_ID,
    CITY_NAME,
    STATE,
    COUNTRY,
    REGION,
    POPULATION,
    AREA_SQKM,
    CITY_CLASS,
    GEO_TYPE,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME,
    BATCH_ID
)
FROM
(
    SELECT
        $1::VARCHAR,
        $2::VARCHAR,
        $3::VARCHAR,
        $4::VARCHAR,
        $5::VARCHAR,
        $6::NUMBER,
        $7::NUMBER(12,2),
        $8::VARCHAR,
        $9::VARCHAR,
        $10::TIMESTAMP_NTZ,
        METADATA$START_SCAN_TIME::TIMESTAMP_NTZ,
        METADATA$FILENAME,
        MD5(METADATA$FILENAME)
    FROM @RE_S3_STAGE/cities/
)
FILE_FORMAT = (
    FORMAT_NAME = 'FF_REAL_ESTATE_CSV'
)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE PIPE PIPE_DEVELOPERS
    AUTO_INGEST = FALSE
AS
COPY INTO RAW_DEVELOPERS
(
    DEVELOPER_ID,
    DEVELOPER_NAME,
    HQ_COUNTRY,
    DEVELOPER_TIER,
    FOCUS_SEGMENT,
    HQ_CITY,
    HQ_STATE,
    STATUS,
    PARTNER_SINCE,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME,
    BATCH_ID
)
FROM
(
    SELECT
        $1::VARCHAR,
        $2::VARCHAR,
        $3::VARCHAR,
        $4::VARCHAR,
        $5::VARCHAR,
        $6::VARCHAR,
        $7::VARCHAR,
        $8::VARCHAR,
        $9::DATE,
        $10::TIMESTAMP_NTZ,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME,
        MD5(METADATA$FILENAME)
    FROM @RE_S3_STAGE/developers/
)
FILE_FORMAT = (
    FORMAT_NAME = 'FF_REAL_ESTATE_CSV'
)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE PIPE PIPE_PROPERTIES
    AUTO_INGEST = FALSE
AS
COPY INTO RAW_PROPERTIES
(
    PROPERTY_ID,
    CITY_ID,
    DEVELOPER_ID,
    PROPERTY_TYPE,
    SEGMENT,
    BHK,
    AREA_SQFT,
    POSSESSION_YEAR,
    PROJECT_STATUS,
    AMENITY_TIER,
    RERA_ID,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME,
    BATCH_ID
)
FROM
(
    SELECT
        $1::VARCHAR,
        $2::VARCHAR,
        $3::VARCHAR,
        $4::VARCHAR,
        $5::VARCHAR,
        $6::NUMBER,
        $7::NUMBER,
        $8::NUMBER,
        $9::VARCHAR,
        $10::VARCHAR,
        $11::VARCHAR,
        $12::TIMESTAMP_NTZ,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME,
        MD5(METADATA$FILENAME)
    FROM @RE_S3_STAGE/properties/
)
FILE_FORMAT = (
    FORMAT_NAME = 'FF_REAL_ESTATE_CSV'
)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE PIPE PIPE_TRANSACTIONS
    AUTO_INGEST = FALSE
AS
COPY INTO RAW_TRANSACTIONS
(
    TXN_ID,
    TXN_LINE_ID,
    TXN_DATE,
    PROPERTY_ID,
    CITY_ID,
    DEVELOPER_ID,
    BUYER_SEGMENT,
    LIST_PRICE_LAKHS,
    DISCOUNT_PCT,
    SALE_PRICE_LAKHS,
    LOAN_REQUIRED,
    SALES_CHANNEL,
    TXN_STATUS,
    PAYMENT_MODE,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME,
    BATCH_ID
)
FROM
(
    SELECT
        $1::VARCHAR,
        $2::NUMBER,
        $3::DATE,
        $4::VARCHAR,
        $5::VARCHAR,
        $6::VARCHAR,
        $7::VARCHAR,
        $8::NUMBER(18,2),
        $9::NUMBER(5,2),
        $10::NUMBER(18,2),
        $11::VARCHAR,
        $12::VARCHAR,
        $13::VARCHAR,
        $14::VARCHAR,
        $15::TIMESTAMP_NTZ,
        CURRENT_TIMESTAMP(),
        METADATA$FILENAME,
        MD5(METADATA$FILENAME)
    FROM @RE_S3_STAGE/transactions/
)
FILE_FORMAT = (
    FORMAT_NAME = 'FF_REAL_ESTATE_CSV'
)
ON_ERROR = 'CONTINUE';



SHOW PIPES IN SCHEMA REAL_ESTATE_ANALYTICS.RAW;

DESC PIPE PIPE_CITIES;
DESC PIPE PIPE_DEVELOPERS;
DESC PIPE PIPE_PROPERTIES;
DESC PIPE PIPE_TRANSACTIONS;
