USE ROLE ACCOUNTADMIN;

USE DATABASE REAL_ESTATE_ANALYTICS;
USE SCHEMA RAW;
SHOW PARAMETERS LIKE 'TIMEZONE' IN SESSION;

LIST @REAL_ESTATE_ANALYTICS.RAW.RE_S3_STAGE;


ALTER PIPE PIPE_CITIES SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE PIPE_DEVELOPERS SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE PIPE_PROPERTIES SET PIPE_EXECUTION_PAUSED = FALSE;
ALTER PIPE PIPE_TRANSACTIONS SET PIPE_EXECUTION_PAUSED = FALSE;

ALTER PIPE PIPE_CITIES REFRESH;

ALTER PIPE PIPE_DEVELOPERS REFRESH;

ALTER PIPE PIPE_PROPERTIES REFRESH;

ALTER PIPE PIPE_TRANSACTIONS REFRESH;



show tables;

select * from raw_cities;
select * from raw_developers;
select * from raw_properties;
select * from raw_transactions;

SELECT COUNT(*) AS ROW_COUNT
FROM REAL_ESTATE_ANALYTICS.RAW.RAW_CITIES;

SELECT COUNT(*) AS ROW_COUNT
FROM REAL_ESTATE_ANALYTICS.RAW.RAW_DEVELOPERS;

SELECT COUNT(*) AS ROW_COUNT
FROM REAL_ESTATE_ANALYTICS.RAW.RAW_PROPERTIES;

SELECT COUNT(*) AS ROW_COUNT
FROM REAL_ESTATE_ANALYTICS.RAW.RAW_TRANSACTIONS;

SELECT SYSTEM$PIPE_STATUS('REAL_ESTATE_ANALYTICS.RAW.PIPE_CITIES');
SELECT SYSTEM$PIPE_STATUS('REAL_ESTATE_ANALYTICS.RAW.PIPE_DEVELOPERS');

SELECT SYSTEM$PIPE_STATUS('REAL_ESTATE_ANALYTICS.RAW.PIPE_PROPERTIES');

SELECT SYSTEM$PIPE_STATUS('REAL_ESTATE_ANALYTICS.RAW.PIPE_TRANSACTIONS');


SELECT
    CITY_ID,
    CITY_NAME,
    UPDATED_AT,
    LOAD_TS,
    SOURCE_FILE_NAME,
    BATCH_ID
FROM REAL_ESTATE_ANALYTICS.RAW.RAW_CITIES
ORDER BY CITY_ID
LIMIT 5;

ALTER SESSION SET TIMEZONE = 'Asia/Kolkata';

LIST @REAL_ESTATE_ANALYTICS.RAW.RE_S3_STAGE/cities/;
LIST @REAL_ESTATE_ANALYTICS.RAW.RE_S3_STAGE/developers/;
LIST @REAL_ESTATE_ANALYTICS.RAW.RE_S3_STAGE/properties/;
LIST @REAL_ESTATE_ANALYTICS.RAW.RE_S3_STAGE/transactions/;