USE DATABASE REAL_ESTATE_ANALYTICS;
create schema OPS;
USE SCHEMA OPS;

CREATE OR REPLACE TABLE REJECTS
(
    REJECT_ID               VARCHAR,
    PIPE_NAME               VARCHAR,
    TABLE_NAME              VARCHAR,
    FILE_NAME               VARCHAR,

    ROWS_PARSED             NUMBER,
    ROWS_LOADED             NUMBER,
    ERROR_COUNT             NUMBER,

    REASON_CODE             VARCHAR,
    ERROR_LINE_NUMBER       NUMBER,
    ERROR_CHARACTER_POS     NUMBER,
    ERROR_COLUMN_NAME       VARCHAR,

    DETECTED_TS             TIMESTAMP_LTZ
);

DESC TABLE OPS.REJECTS;



-- SELECT
--     FILE_NAME,
--     PIPE_NAME,
--     TABLE_NAME,
--     ROW_PARSED,
--     ROW_COUNT,
--     ERROR_COUNT,
--     FIRST_ERROR_MESSAGE,
--     FIRST_ERROR_LINE_NUMBER,
--     FIRST_ERROR_CHARACTER_POS,
--     FIRST_ERROR_COLUMN_NAME,
--     STATUS,
--     LAST_LOAD_TIME
-- FROM TABLE(
--     INFORMATION_SCHEMA.COPY_HISTORY(
--         TABLE_NAME => 'RAW.RAW_TRANSACTIONS',
--         START_TIME => DATEADD('DAY', -1, CURRENT_TIMESTAMP())
--     )
-- )
-- ORDER BY LAST_LOAD_TIME DESC;



USE DATABASE REAL_ESTATE_ANALYTICS;

INSERT INTO OPS.REJECTS
(
    REJECT_ID,
    PIPE_NAME,
    TABLE_NAME,
    FILE_NAME,
    ROWS_PARSED,
    ROWS_LOADED,
    ERROR_COUNT,
    REASON_CODE,
    ERROR_LINE_NUMBER,
    ERROR_CHARACTER_POS,
    ERROR_COLUMN_NAME,
    DETECTED_TS
)
SELECT
    MD5(
        PIPE_NAME || '|' ||
        FILE_NAME || '|' ||
        COALESCE(FIRST_ERROR_MESSAGE, '') || '|' ||
        LAST_LOAD_TIME::VARCHAR
    ) AS REJECT_ID,

    PIPE_NAME,
    TABLE_NAME,
    FILE_NAME,
    ROW_PARSED,
    ROW_COUNT,
    ERROR_COUNT,

    -- Store Snowflake's actual error as the reason
    FIRST_ERROR_MESSAGE,

    FIRST_ERROR_LINE_NUMBER,
    FIRST_ERROR_CHARACTER_POS,
    FIRST_ERROR_COLUMN_NAME,

    CURRENT_TIMESTAMP()

FROM TABLE(
    INFORMATION_SCHEMA.COPY_HISTORY(
        TABLE_NAME => 'RAW.RAW_TRANSACTIONS',
        START_TIME => DATEADD('DAY', -1, CURRENT_TIMESTAMP())
    )
)
WHERE FILE_NAME = 're_transactions_bad1.csv'
  AND ERROR_COUNT > 0;

SELECT *
FROM OPS.REJECTS
ORDER BY DETECTED_TS DESC;

show tables;