CREATE OR REPLACE TASK OPS.TASK_CAPTURE_REJECTS
    WAREHOUSE = RE_ETL_WH
    SCHEDULE = '1 MINUTE'
AS

MERGE INTO OPS.REJECTS T
USING
(
    SELECT
        MD5(
            PIPE_NAME || '|' ||
            FILE_NAME || '|' ||
            COALESCE(FIRST_ERROR_MESSAGE, '') || '|' ||
            LAST_LOAD_TIME::VARCHAR
        ) AS REJECT_ID,

        PIPE_NAME,
        TABLE_NAME,
        FILE_NAME,

        ROW_PARSED AS ROWS_PARSED,
        ROW_COUNT AS ROWS_LOADED,
        ERROR_COUNT,

        FIRST_ERROR_MESSAGE AS REASON_CODE,
        FIRST_ERROR_LINE_NUMBER AS ERROR_LINE_NUMBER,
        FIRST_ERROR_CHARACTER_POS AS ERROR_CHARACTER_POS,
        FIRST_ERROR_COLUMN_NAME AS ERROR_COLUMN_NAME,

        LAST_LOAD_TIME

    FROM TABLE
    (
        INFORMATION_SCHEMA.COPY_HISTORY
        (
            TABLE_NAME => 'RAW.RAW_TRANSACTIONS',
            START_TIME => DATEADD('MINUTE', -5, CURRENT_TIMESTAMP())
        )
    )

    WHERE ERROR_COUNT > 0

) S

ON T.REJECT_ID = S.REJECT_ID

WHEN NOT MATCHED THEN

INSERT
(
    REJECT_ID,
    PIPE_NAME,
    TABLE_NAME,
    FILE_NAME,
    ROWS_PARSED,
    ROWS_LOADED,
    ERROR_COUNT,
    REASON_CODE,
    ERROR_LINE_NUMBER,
    ERROR_CHARACTER_POS,
    ERROR_COLUMN_NAME,
    DETECTED_TS
)

VALUES
(
    S.REJECT_ID,
    S.PIPE_NAME,
    S.TABLE_NAME,
    S.FILE_NAME,
    S.ROWS_PARSED,
    S.ROWS_LOADED,
    S.ERROR_COUNT,
    S.REASON_CODE,
    S.ERROR_LINE_NUMBER,
    S.ERROR_CHARACTER_POS,
    S.ERROR_COLUMN_NAME,
    CURRENT_TIMESTAMP()
);

SHOW TASKS LIKE 'TASK_CAPTURE_REJECTS' IN SCHEMA OPS;

ALTER TASK OPS.TASK_CAPTURE_REJECTS RESUME;

SELECT *
FROM OPS.REJECTS
ORDER BY DETECTED_TS DESC;

ALTER TASK OPS.TASK_CAPTURE_REJECTS SUSPEND;